name: Markdown Lint Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1